fix: ci

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,42 +10,42 @@ on:
 jobs:
   test-sol:
     name: Foundry build n test
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@v4
-          with:
-            submodules: recursive
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
 
-        - uses: bgd-labs/action-rpc-env@main
-          with:
-            ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
+      - uses: bgd-labs/action-rpc-env@main
+        with:
+          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
 
-        # we simply use foundry zk for all jobs in this repo
-        - name: Run Foundry setup
-          uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main
-          with:
-            ZKSYNC: "true"
+      # we simply use foundry zk for all jobs in this repo
+      - name: Run Foundry setup
+        uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main
+        with:
+          ZKSYNC: "true"
 
-        - name: Run Forge tests
-          id: test
-          uses: bgd-labs/github-workflows/.github/actions/foundry-test@main
-          with:
-            MODE: "CHANGED"
+      - name: Run Forge tests
+        id: test
+        uses: bgd-labs/github-workflows/.github/actions/foundry-test@main
+        with:
+          MODE: "CHANGED"
 
-        - name: Run ZK tests
-          id: zktest
-          uses: bgd-labs/github-workflows/.github/actions/foundry-test@main
-          with:
-            MODE: "CHANGED"
-            ZKSYNC: true
-            ROOT_DIR: "zksync"
+      - name: Run ZK tests
+        id: zktest
+        uses: bgd-labs/github-workflows/.github/actions/foundry-test@main
+        with:
+          MODE: "CHANGED"
+          ZKSYNC: true
+          ROOT_DIR: "zksync"
 
-        - name: Run Forge tests
-          uses: bgd-labs/github-workflows/.github/actions/comment-artifact@main
+      - name: Run Forge tests
+        uses: bgd-labs/github-workflows/.github/actions/comment-artifact@main
 
-        # we let failing tests pass so we can log them in the comment, still we want the ci to fail
-        - name: Post test
-          if: ${{ steps.test.outputs.testStatus != 0 || steps.zktest.outputs.testStatus != 0 }}
-          run: |
-            echo "tests failed"
-            exit 1
+      # we let failing tests pass so we can log them in the comment, still we want the ci to fail
+      - name: Post test
+        if: ${{ steps.test.outputs.testStatus != 0 || steps.zktest.outputs.testStatus != 0 }}
+        run: |
+          echo "tests failed"
+          exit 1
